### ISSUE TITLE
Error when running heroku run python manage.py send_scheduled_mail

### ISSUE THREAD

**Issue by 1l2p** [p2pu/mechanical-mooc#1]
This is one of the last instruction in the installation how-to. It throws the following error. I suspect something went wrong earlier (I'll post other errors I received as separate issues).

172-30-3-198:agile-dawn-4975 P$ heroku run python manage.py send_scheduled_mail
Running `python manage.py send_scheduled_mail` attached to terminal... up, run.8735
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/app/mail/management/commands/send_scheduled_mail.py", line 13, in handle
    emails = mail_api.get_emails()
  File "/app/mail/models.py", line 73, in get_emails
    return [_2json(em) for em in db.Email.objects.all()]
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 892, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)
django.db.utils.DatabaseError: relation "mail_email" does not exist
LINE 1: ..."."date_scheduled", "mail_email"."date_sent" FROM "mail_emai...

**Comment by sohel7867** [comment]
python: can't open file 'manage': [Errno 2] No such file or directory , i am getting this error
